### ISSUE TITLE
CSS3新属性：rem

### ISSUE THREAD

**Issue by shenjun1992722** [shenjun1992722/blog#2]
### rem为单位（设置字体大小）

　　CSS3的出现，他同时引进了一些新的单位，包括我们今天所说的rem。在W3C官网上是这样描述rem的——“font size of the root element” 。下面我们就一起来详细的了解rem。

　　“em”是相对于其父元素来设置字体大小的，这样就会存在一个问题，进行任何元素设置，都有可能需要知道他父元素的大小，在我们多次使用时，就会带来无法预知的错误风险。而rem是相对于根元素<html>，这样就意味着，我们只需要在根元素确定一个参考值，，在根元素中设置多大的字体，这完全可以根据您自己的需，大家也可以参考下图：
![这里写图片描述](https://raw.githubusercontent.com/shenjun1992722/MarkdownPhotos/master/emTable.png)

我们来看一个简单的代码实例：

``` css
html {font-size: 62.5%; }　/*10 ÷ 16 × 100% = 62.5%*/
body {font-size: 1.4rem;  /*1.4 × 10px = 14px */}
h1 { font-size: 2.4rem;  /*2.4 × 10px = 24px*/}
```

　　我在根元素<html>中定义了一个基本字体大小为62.5%（也就是10px。设置这个值主要方便计算，如果没有设置，将是以“16px”为基准 ）。从上面的计算结果，我们使用“rem”就像使用“px”一样的方便，而且同时解决了“px”和“em”两者不同之处。

　　不过使用单位设置字体，可不能完全不考虑IE了，如果你想使用这个REM，但也想兼容IE下的效果，可你可考虑“px”和“rem”一起使用，用"px"来实现IE6-8下的效果，然后使用“Rem”来实现代浏览器的效果。

[转自 CSS3的REM设置字体大小 ](http://www.w3cplus.com/css3/define-font-size-with-css3-rem)

　　在移动端可以做到适配不同的手机分辨率，如果保持整体缩放，没有设计上的差异可以不需要用到`media query`
　　假设设计师的视觉稿是按照iPhone6的宽度来设计的，即375px (如果是高清的视觉稿750/2=375)那么，我们可以完全按照视觉稿上的尺寸来赋值给元素的样式，比如视觉稿上的尺寸是80px，那么在css中就可以直接定义width:80px;  页面中所有的尺寸都这样来设置。

当所有的网站所有的页面样式都设置好之后。我们需要做两件事情：
1. 设置页面的rem大小

``` css
html {
font-size: calc(100vw/3.75);
}
```

100vw是设备的宽度，除以3.75可以让1rem的大小在iPhone6下等于100px
1. 替换页面中的单位，把所有的px单位替换成rem，除以100，比如前面的80px，就是0.8rem这样在iPhone6下，所有元素的尺寸还是和视觉稿的尺寸一样，而iphone5中，因为设备的宽度变小了，100vw/3.75得到的值，会相应的变小，即rem的单位值会变小，页面中所有的尺寸会等比例缩放。
   　　这样就可以做到针对任何分辨率的设备保持视觉一致了。
   　　最后，前面用到vw单位，但是低版本的设备可能不支持，那么就需要js来处理一下：

``` javascript
document.documentElement.style.fontSize = window.innerWidth/3.75 + 'px'
```

　　之所以前面让1rem等于100px，而不是1rem等于1px，是因为在chrome下针对中文的最小字体是12px。
　　当然，这种步骤是针对现在的状况改rem来做的，如果一开始就是使用rem，那么写css的时候，可以直接写rem单位，按视觉稿除以100，其实也没有什么计算过程。或者用预处理器的话，也可以写一个`px2rem`的函数，直接改这个函数就可以了。

[转自知乎 作者：sapjax](http://www.zhihu.com/question/21504656/answer/48542422)
